volumes:
  postgresql-data:

services:
  service:
    build:
      dockerfile: Dockerfile
      context: .

    volumes:
      - ./settings.yaml:/app/settings.yaml
      - ./.secrets.yaml:/app/.secrets.yaml
      - ./addons:/app/addons

    ports:
      - "${APP_PORT}:8000"

    restart: unless-stopped